services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Mindshape\MindshapeSeo\:
    resource: '../Classes/*'
    exclude: '../Classes/{Domain/Model,Utility}'

  Mindshape\MindshapeSeo\Backend\Form\Element\GooglePreviewElementV12:
    autowire: false

  Mindshape\MindshapeSeo\Controller\BackendController:
    tags: [ 'backend.controller' ]
